- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Update cache and install apt-transport-https package to allow apt to use a repository over HTTPS
      apt:
        name: apt-transport-https
        update_cache: yes

    - name: Install ca-certificates package
      apt:
        name: ca-certificates

    - name: Install gnupg-agent package
      apt:
        name: gnupg-agent

    - name: Install software-properties-common package
      apt:
        name: software-properties-common

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker's APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker-ce
      apt:
        name: docker-ce
        update_cache: yes

    - name: Install docker-ce-cli
      apt:
        name: docker-ce-cli

    - name: Install containerd.io
      apt:
        name: containerd.io
        
    - name: Add user to the docker group to avoid running all docker commands with sudo
      user:
        name: aleksei
        groups: docker
        append: yes